preload = /home/eydriannn/Pictures/Wallpapers/moon.jpg
wallpaper {
    monitor = eDP-1
    path = /home/eydriannn/Pictures/Wallpapers/moon.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/eydriannn/Pictures/Wallpapers/moon.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = /home/eydriannn/Pictures/Wallpapers/moon.jpg
    fit_mode = cover
}
