#################
### AUTOSTART ###
#################
exec-once = waybar
exec-once = systemctl --user start swaync 2>/dev/null || swaync
exec-once = [workspace 1 silent] brave
exec-once = [workspace 2 silent] cursor
exec-once = [workspace 3 silent] kitty
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset --temperature 4000
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = $wallpaperScript --init
