#############################
### ENVIRONMENT VARIABLES ###
#############################
env = PATH,/home/eydriannn/.local/bin:/home/eydriannn/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_THEME,Bibata-Modern-Ice
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = GDK_SCALE,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto
