###################
### MY PROGRAMS ###
###################
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$wallpaperScript = ~/.config/hypr/scripts/wallpaper.sh
$powermenu = wlogout
$mainMod = SUPER
