###################
### MY PROGRAMS ###
###################
$terminal = kitty
$fileManager = nautilus
$menu = quickshell ipc call launcher toggle
$wallpaperScript = ~/.config/hypr/scripts/wallpaper.sh
$powermenu = quickshell ipc call powermenu toggle
$mainMod = SUPER
